language: php

php:
  - 5.3
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

install: pip install jsonrpclib

before_script:
  - composer install --prefer-source
  - python ./test/resources/serve.py &

script: ./vendor/bin/phpunit