language: php

php:
  - 5.4
  - 5.5
  - 5.6
  - 7
  - hhvm

install: sudo pip install jsonrpclib

before_script:
  - composer install --prefer-source
  - python $TRAVIS_BUILD_DIR/tests/resources/serve.py &

script: ./vendor/bin/phpunit --coverage-text --coverage-clover=coverage.clover

after_script:
  - bash -c 'if [[ "$TRAVIS_PHP_VERSION" != "hhvm" && "$TRAVIS_PHP_VERSION" != 7* ]]; then php vendor/bin/ocular code-coverage:upload --format=php-clover coverage.clover; fi;'
